kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/kamkie/ubuntu-jenkins-slave'
  name: ubuntu-jenkins-slave
  namespace: jenkins2
  labels:
    app: ubuntu-jenkins-slave
    app.kubernetes.io/component: ubuntu-jenkins-slave
    app.kubernetes.io/instance: ubuntu-jenkins-slave
    app.kubernetes.io/part-of: ubuntu-jenkins-slave-app
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'ubuntu-jenkins-slave:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/kamkie/ubuntu-jenkins-slave'
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: ubuntu-jenkins-slave-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: ubuntu-jenkins-slave-github-webhook-secret
    - type: ConfigChange
  runPolicy: Serial
